ACMS-1206: Added code for providing staterkit options.
acquia/acquia_cms_tour pull request #4
Opened 2022-06-01 16:18 UTC by panshulK

2022-06-07 04:40 UTC, vishalkhode1 requested changes

2022-06-07 04:40 UTC, vishalkhode1 commented on src/Controller/DashboardController.php
> +    $selected_starter_kit = $this->state->get('starter_kit_selected', FALSE);
@panshulK This won't be true|false. It would be the name of the starter-kit selected. Let's user the state name same that we are using with acquia-cms-starterkit. https://github.com/acquia/acquia-cms-starterkit/blob/1.0.0-beta1/src/Helpers/Task/Steps/EnableThemes.php#L78

2022-06-07 04:40 UTC, vishalkhode1 commented on src/Controller/DashboardController.php
> +      '#title' => 'Starter Template set-up',
@panshulK Use `t` function to translate.

2022-06-07 19:00 UTC, panshulK commented
@vishalkhode1 identified and fixed the syntax error issues. Please re-review.
Thanks

2022-06-08 11:51 UTC, vishalkhode1 approved these changes

2022-06-08 11:51 UTC, merged