ACMS-1242: Update UI installation to ask for questions
acquia/acquia_cms_tour pull request #8
Opened 2022-06-20 11:24 UTC by rajeshreeputra

2022-06-21 05:28 UTC, rajeshreeputra commented
> @rajeshreeputra - On `admin/tour/dashboard` page I can see wizard option for selecting starterkit, but after selection I can also see a message that should only appear, if that are no module enable. we need to check that. ![image](https://user-images.githubusercontent.com/63041696/174623405-1bfc0c12-284c-4269-b67c-1e641535bdea.png)
> 
> Also, on wizard page I can see message like `Fields marked * are required' but I don't see any field required, do we need that message. ![image](https://user-images.githubusercontent.com/63041696/174623655-7afc4932-6888-4979-a5aa-5b3f89a13e05.png)
> 
> Lastly, we should trigger wizard setup automatically once user done with setting up starter kit, this is not happening currently.


- Removed `Fields marked * are required' message
- Installation wizard set to trigger automatically after starter kit selection

2022-06-21 05:35 UTC, panshulK requested changes

2022-06-21 05:35 UTC, panshulK commented on src/Form/SelectionWizardForm.php
> +class SelectionWizardForm extends FormBase {
@rajeshreeputra , @vishalkhode1, @chandan-singh7929  Shouldn't we change the class file name to something that indicates the functionality implemented? Something more apt. like - QuestionWizardForm ?

2022-06-21 05:35 UTC, panshulK commented on src/Form/StarterKitSelectionForm.php
> +        '#markup' => '<p>' . $this->t("Acquia CMS starter kits provide different starting points for your site depending on your requirements. Select a from one of the starter kits below to enable th
Grammatical error - "Select a from". @rajeshreeputra 

Also, I think. we need to re-write this - "Acquia CMS starter kits provide different starting points for your site depending on your requirements. Select a from one of the starter kits below to enable the modules."

Suggestions @chandan-singh7929 @vishalkhode1 ?

2022-06-21 05:35 UTC, panshulK commented on src/Form/StarterKitSelectionForm.php
> +      '#title' => $this->t('Do you want a demo with demo content (yes/no) ?'),
@vishalkhode1  @chandan-singh7929  @rajeshreeputra  need suggestion here as well. Language of the question can be changed IMO.

2022-06-21 05:38 UTC, rajeshreeputra commented on src/Form/SelectionWizardForm.php
> +class SelectionWizardForm extends FormBase {
okay we can change the class file name to StarterKitSelectionWizardForm

2022-06-21 05:38 UTC, panshulK commented
> > @rajeshreeputra - On `admin/tour/dashboard` page I can see wizard option for selecting starterkit, but after selection I can also see a message that should only appear, if that are no module enable. we need to check that. ![image](https://user-images.githubusercontent.com/63041696/174623405-1bfc0c12-284c-4269-b67c-1e641535bdea.png)
> > Also, on wizard page I can see message like `Fields marked * are required' but I don't see any field required, do we need that message. ![image](https://user-images.githubusercontent.com/63041696/174623655-7afc4932-6888-4979-a5aa-5b3f89a13e05.png)
> > Lastly, we should trigger wizard setup automatically once user done with setting up starter kit, this is not happening currently.
> 
> * Removed `Fields marked * are required' message
> * Installation wizard set to trigger automatically after starter kit selection

The form (actual selections) can be center aligned. @rajeshreeputra

2022-06-21 06:25 UTC, rajeshreeputra commented on src/Form/StarterKitSelectionForm.php
> +        '#markup' => '<p>' . $this->t("Acquia CMS starter kits provide different starting points for your site depending on your requirements. Select a from one of the starter kits below to enable th
updated

2022-06-23 15:33 UTC, vishalkhode1 commented on js/acquia_cms_tour_dashboard.js
> +        var checkStarterKitExist = setInterval(function() {
@rajeshreeputra Any reason for using setInterval. I think we should definitely not use it here  and same for below.

2022-06-27 05:39 UTC, vishalkhode1 approved these changes

2022-06-27 05:39 UTC, merged